# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 03:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('wave', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[], size=None)),
                ('sr', models.IntegerField(default=16000)),
                ('label', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'db_table': 'sound',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('gender', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
