# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(default='')),
            ],
            options={
                'db_table': 'sound',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('gender', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
