# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_sound_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Users'),
        ),
    ]
